spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huaizhen
    username: root
    password:

jwt:
  secret: yourSecretKeyHere123456789892435682439065802934658
  expiration: 3600000  # 1小时（毫秒）
